---
- name: Provision Vagrant
  hosts: localhost
  become: True
  # gather_facts: True
  tasks:
    - name: Install unzip to extract the downloaded zip
      apt:
        name: unzip
        state: latest
        update_cache: True

    - name: Make temporary directory to download the terraform binary
      file:
        path: /opt/terraform
        state: directory
        mode: 0755

    - name: Download the zip from remote URL
      get_url:
        url: https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip?_ga=2.187980712.1672515446.1521867949-372633631.1519361072
        dest: /opt/terraform/terraform.zip

    - name: Extract the zip
      unarchive:
        src: /opt/terraform/terraform.zip
        dest: /usr/local/bin/
        remote_src: True

    - name: Remove the temporary download directory
      file:
       path: /opt/terraform
       state: absent

    - name: Install nginx to serve for jenkins later
      apt:
        name: nginx
        state: latest
        update_cache: True

    - name: Add the apt repo key for jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present

    - name: Add the apt repo for jenkins
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install jenkins
      apt:
       name: jenkins
       state: present
       update_cache: True

    - name: Start jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Copy the jenkins config
      copy:
        src: jenkins.conf
        dest: /etc/nginx/sites-available/
        owner: root

    - name: Link the jenkins config to sites-enabled
      file:
        src: /etc/nginx/sites-available/jenkins.conf
        dest: /etc/nginx/sites-enabled/jenkins.conf
        state: link

    - name: Remove the existing default sites
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Reload nginx for proxying jenkins via nginx
      service:
        name: nginx
        state: reloaded
